[project]
name = "bridge"
requirements = []

[clarigen]
output_dir = "common/clarigen"
docs = "docs"

[contracts.ft-trait]
path = "contracts/ft-trait.clar"
depends_on = []

[contracts.test-utils]
path = "contracts/test/test-utils.clar"
depends_on = []

[contracts.xbtc]
path = "contracts/xbtc.clar"
depends_on = ["ft-trait"]

[contracts.clarity-bitcoin]
path = "contracts/clarity-bitcoin.clar"
depends_on = ["test-utils"]

[contracts.bridge]
path = "contracts/bridge.clar"
depends_on = ["xbtc", "clarity-bitcoin"]

[contracts.supplier-wrapper]
path = "contracts/supplier-wrapper.clar"
depends_on = ["bridge", "xbtc"]
